title: JK-Design
author:
  name: Blu3Monkey
  email: noreply@blu3monkey.com
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email:
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'
links:
  -
    title: Services
    url: '#services'
  -
    title: Portfolio
    url: '#portfolio'
  -
    title: About
    url: '#about'
  -
    title: Contact
    url: '#contact'
social:
  -
    title: facebook
    url: 'https://facebook.com/jk.design.nn'
  -
    title: instagram
    url: 'https://instagram.com/jk.lasecki'
address:
